### PR TITLE
syntax suggestions

### PR DESCRIPTION
**Pull request by danlangford**
we can discuss these syntax suggestions here on this thread if you would like to learn. more about why im suggesting the change I am

### CODE REVIEW

**Comment by ChalaniEkanayake** [comment]
The syntax suggestions make sense. Thank you!

But why is using `List` preferred over `ArrayList`?

**Comment by TransitionWhich** [comment]
The syntax suggestions make sense. Thank you!

But why is using `List` preferred over `ArrayList`?

**Comment by danlangford** [comment]
So it’s generally a good practice to get used to writing your code to an interface that loosely describes the behavior you need. 

A List is an ordered collection
A Set is a unique collection
A Map is a 2-part lookup collection. Use a Key to lookup a Value

so an ArrayList or a TreeSet or a HashMap are specific implementations of the general behavior. Where possible you want to code to the generic behavior so that you can change out the implementation easily without needing to change ALL your code around. Maybe for a specific task a LinkedList or a CopyOnWrite would be better. You can swap out implementations easier. https://docs.oracle.com/javase/tutorial/collections/implementations/list.html

When you want a Set (a unique collection) there are a couple implementations. I usually use a TreeSet implementation because i often like the auto sorting I get. https://docs.oracle.com/javase/tutorial/collections/implementations/set.html

If you know you need the ability to look up a Value given a Key then you code to a Map interface. But the specific implementation can have different behaviors like a HashMap or TreeMap or ConcurrentMap. https://docs.oracle.com/javase/tutorial/collections/implementations/map.html

Your code has two sides. You have one spot in your code where you define the interaction and the data structures, and you have another part of your code that executes/uses/leverages what was defined. When you define your interaction you want to code to the lowest necessary interface that describes the behavior that this specific method needs. You might know that this will only ever be implemented by a ordered list but if this specific function does not need any List type behavior you might consider having the parameter just be the Collection class. 

Really though, most the time you are using a List consider if you actually want a Set 

hopefully you could follow a little of that stream of consciousness. 

Good luck and let me know if I can help. Be sure to @mention me so I get a notification

**Comment by TransitionWhich** [comment]
Thank you for the insights. 

> So it’s generally a good practice to get used to writing your code to an interface that loosely describes the behavior you need.

I started going through the Head First Design Patterns book because many recommended that and this was also mentioned in that book. 
Seems like it is better to have an understanding of design patterns before blindly starting to code.

**Pull request merged**
